# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        Mmi\*MmitvBundle\Entity\User: sha512

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
       ROLE_REDAC:       ROLE_USER
       ROLE_ADMIN:       [ROLE_USER, ROLE_REDAC]
       ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_REDAC, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        main:
            id: fos_user.user_provider.username

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # Firewall principal :
        main:
             pattern:        ^/
             anonymous:      true
             provider:       main
             form_login:
               login_path: fos_user_security_login
               check_path: fos_user_security_check
             logout:
                path:       fos_user_security_logout
                target:     /
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_REDAC }
        - { path: ^/gestionutilisateur, role: ROLE_ADMIN }