# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    acme_user.registration.form.type:
        class: Mmi\MmitvBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: mmi_mmitv_registration }
    acme_user.profile.form.type:
        class: Mmi\MmitvBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: mmi_mmitv_profil }
