services:
#    mmi_mmitv.example:
#        class: Mmi\MmitvBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    acme_user.registration.form.type:
        class: Mmi\MmitvBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: mmi_mmitv_registration }
    acme_user.profile.form.type:
        class: Mmi\MmitvBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: mmi_mmitv_profil }
